package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AdminSystemConfigsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdminSystemConfigsAllPropertiesEquals(AdminSystemConfigs expected, AdminSystemConfigs actual) {
        assertAdminSystemConfigsAutoGeneratedPropertiesEquals(expected, actual);
        assertAdminSystemConfigsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdminSystemConfigsAllUpdatablePropertiesEquals(AdminSystemConfigs expected, AdminSystemConfigs actual) {
        assertAdminSystemConfigsUpdatableFieldsEquals(expected, actual);
        assertAdminSystemConfigsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdminSystemConfigsAutoGeneratedPropertiesEquals(AdminSystemConfigs expected, AdminSystemConfigs actual) {
        assertThat(actual)
            .as("Verify AdminSystemConfigs auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdminSystemConfigsUpdatableFieldsEquals(AdminSystemConfigs expected, AdminSystemConfigs actual) {
        assertThat(actual)
            .as("Verify AdminSystemConfigs relevant properties")
            .satisfies(a -> assertThat(a.getConfigKey()).as("check configKey").isEqualTo(expected.getConfigKey()))
            .satisfies(a -> assertThat(a.getConfigValue()).as("check configValue").isEqualTo(expected.getConfigValue()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getConfigValueType()).as("check configValueType").isEqualTo(expected.getConfigValueType()))
            .satisfies(a -> assertThat(a.getConfigCategory()).as("check configCategory").isEqualTo(expected.getConfigCategory()))
            .satisfies(a -> assertThat(a.getConfigFile()).as("check configFile").isEqualTo(expected.getConfigFile()))
            .satisfies(a ->
                assertThat(a.getConfigFileContentType()).as("check configFile contenty type").isEqualTo(expected.getConfigFileContentType())
            )
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdminSystemConfigsUpdatableRelationshipsEquals(AdminSystemConfigs expected, AdminSystemConfigs actual) {
        // empty method
    }
}
