package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AdminAnnouncementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdminAnnouncementAllPropertiesEquals(AdminAnnouncement expected, AdminAnnouncement actual) {
        assertAdminAnnouncementAutoGeneratedPropertiesEquals(expected, actual);
        assertAdminAnnouncementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdminAnnouncementAllUpdatablePropertiesEquals(AdminAnnouncement expected, AdminAnnouncement actual) {
        assertAdminAnnouncementUpdatableFieldsEquals(expected, actual);
        assertAdminAnnouncementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdminAnnouncementAutoGeneratedPropertiesEquals(AdminAnnouncement expected, AdminAnnouncement actual) {
        assertThat(actual)
            .as("Verify AdminAnnouncement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdminAnnouncementUpdatableFieldsEquals(AdminAnnouncement expected, AdminAnnouncement actual) {
        assertThat(actual)
            .as("Verify AdminAnnouncement relevant properties")
            .satisfies(a -> assertThat(a.getAnnouncementType()).as("check announcementType").isEqualTo(expected.getAnnouncementType()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getAnnouncerId()).as("check announcerId").isEqualTo(expected.getAnnouncerId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdminAnnouncementUpdatableRelationshipsEquals(AdminAnnouncement expected, AdminAnnouncement actual) {
        // empty method
    }
}
