package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AdminEmailConfigsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdminEmailConfigsAllPropertiesEquals(AdminEmailConfigs expected, AdminEmailConfigs actual) {
        assertAdminEmailConfigsAutoGeneratedPropertiesEquals(expected, actual);
        assertAdminEmailConfigsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdminEmailConfigsAllUpdatablePropertiesEquals(AdminEmailConfigs expected, AdminEmailConfigs actual) {
        assertAdminEmailConfigsUpdatableFieldsEquals(expected, actual);
        assertAdminEmailConfigsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdminEmailConfigsAutoGeneratedPropertiesEquals(AdminEmailConfigs expected, AdminEmailConfigs actual) {
        assertThat(actual)
            .as("Verify AdminEmailConfigs auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdminEmailConfigsUpdatableFieldsEquals(AdminEmailConfigs expected, AdminEmailConfigs actual) {
        assertThat(actual)
            .as("Verify AdminEmailConfigs relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getSubject()).as("check subject").isEqualTo(expected.getSubject()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getMailTemplateType()).as("check mailTemplateType").isEqualTo(expected.getMailTemplateType()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdminEmailConfigsUpdatableRelationshipsEquals(AdminEmailConfigs expected, AdminEmailConfigs actual) {
        // empty method
    }
}
