package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AssistanceTicketAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssistanceTicketAllPropertiesEquals(AssistanceTicket expected, AssistanceTicket actual) {
        assertAssistanceTicketAutoGeneratedPropertiesEquals(expected, actual);
        assertAssistanceTicketAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssistanceTicketAllUpdatablePropertiesEquals(AssistanceTicket expected, AssistanceTicket actual) {
        assertAssistanceTicketUpdatableFieldsEquals(expected, actual);
        assertAssistanceTicketUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssistanceTicketAutoGeneratedPropertiesEquals(AssistanceTicket expected, AssistanceTicket actual) {
        assertThat(actual)
            .as("Verify AssistanceTicket auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssistanceTicketUpdatableFieldsEquals(AssistanceTicket expected, AssistanceTicket actual) {
        assertThat(actual)
            .as("Verify AssistanceTicket relevant properties")
            .satisfies(a -> assertThat(a.getSubject()).as("check subject").isEqualTo(expected.getSubject()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getOpenedAt()).as("check openedAt").isEqualTo(expected.getOpenedAt()))
            .satisfies(a -> assertThat(a.getClosedAt()).as("check closedAt").isEqualTo(expected.getClosedAt()))
            .satisfies(a -> assertThat(a.getComments()).as("check comments").isEqualTo(expected.getComments()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssistanceTicketUpdatableRelationshipsEquals(AssistanceTicket expected, AssistanceTicket actual) {
        assertThat(actual)
            .as("Verify AssistanceTicket relationships")
            .satisfies(a -> assertThat(a.getAssignedAdmin()).as("check assignedAdmin").isEqualTo(expected.getAssignedAdmin()))
            .satisfies(a -> assertThat(a.getReport()).as("check report").isEqualTo(expected.getReport()))
            .satisfies(a -> assertThat(a.getDocumentsReview()).as("check documentsReview").isEqualTo(expected.getDocumentsReview()));
    }
}
