package com.monsterdam.app.domain;

import static com.monsterdam.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class AuctionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuctionAllPropertiesEquals(Auction expected, Auction actual) {
        assertAuctionAutoGeneratedPropertiesEquals(expected, actual);
        assertAuctionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuctionAllUpdatablePropertiesEquals(Auction expected, Auction actual) {
        assertAuctionUpdatableFieldsEquals(expected, actual);
        assertAuctionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuctionAutoGeneratedPropertiesEquals(Auction expected, Auction actual) {
        assertThat(actual)
            .as("Verify Auction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuctionUpdatableFieldsEquals(Auction expected, Auction actual) {
        assertThat(actual)
            .as("Verify Auction relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a ->
                assertThat(a.getStartingPrice())
                    .as("check startingPrice")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getStartingPrice())
            )
            .satisfies(a ->
                assertThat(a.getCurrentPrice())
                    .as("check currentPrice")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCurrentPrice())
            )
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getAuctionStatus()).as("check auctionStatus").isEqualTo(expected.getAuctionStatus()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuctionUpdatableRelationshipsEquals(Auction expected, Auction actual) {
        assertThat(actual)
            .as("Verify Auction relationships")
            .satisfies(a -> assertThat(a.getCreator()).as("check creator").isEqualTo(expected.getCreator()))
            .satisfies(a -> assertThat(a.getWinner()).as("check winner").isEqualTo(expected.getWinner()));
    }
}
