package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChatRoomAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatRoomAllPropertiesEquals(ChatRoom expected, ChatRoom actual) {
        assertChatRoomAutoGeneratedPropertiesEquals(expected, actual);
        assertChatRoomAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatRoomAllUpdatablePropertiesEquals(ChatRoom expected, ChatRoom actual) {
        assertChatRoomUpdatableFieldsEquals(expected, actual);
        assertChatRoomUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatRoomAutoGeneratedPropertiesEquals(ChatRoom expected, ChatRoom actual) {
        assertThat(actual)
            .as("Verify ChatRoom auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatRoomUpdatableFieldsEquals(ChatRoom expected, ChatRoom actual) {
        assertThat(actual)
            .as("Verify ChatRoom relevant properties")
            .satisfies(a -> assertThat(a.getLastAction()).as("check lastAction").isEqualTo(expected.getLastAction()))
            .satisfies(a -> assertThat(a.getLastConnectionDate()).as("check lastConnectionDate").isEqualTo(expected.getLastConnectionDate())
            )
            .satisfies(a -> assertThat(a.getMuted()).as("check muted").isEqualTo(expected.getMuted()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()))
            .satisfies(a -> assertThat(a.getParticipantId()).as("check participantId").isEqualTo(expected.getParticipantId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatRoomUpdatableRelationshipsEquals(ChatRoom expected, ChatRoom actual) {
        // empty method
    }
}
