package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CommentMentionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommentMentionAllPropertiesEquals(CommentMention expected, CommentMention actual) {
        assertCommentMentionAutoGeneratedPropertiesEquals(expected, actual);
        assertCommentMentionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommentMentionAllUpdatablePropertiesEquals(CommentMention expected, CommentMention actual) {
        assertCommentMentionUpdatableFieldsEquals(expected, actual);
        assertCommentMentionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommentMentionAutoGeneratedPropertiesEquals(CommentMention expected, CommentMention actual) {
        assertThat(actual)
            .as("Verify CommentMention auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommentMentionUpdatableFieldsEquals(CommentMention expected, CommentMention actual) {
        assertThat(actual)
            .as("Verify CommentMention relevant properties")
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()))
            .satisfies(a -> assertThat(a.getMentionedUserId()).as("check mentionedUserId").isEqualTo(expected.getMentionedUserId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommentMentionUpdatableRelationshipsEquals(CommentMention expected, CommentMention actual) {
        assertThat(actual)
            .as("Verify CommentMention relationships")
            .satisfies(a -> assertThat(a.getOriginPostComment()).as("check originPostComment").isEqualTo(expected.getOriginPostComment()));
    }
}
