package com.monsterdam.app.domain;

import static com.monsterdam.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ContentPackageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContentPackageAllPropertiesEquals(ContentPackage expected, ContentPackage actual) {
        assertContentPackageAutoGeneratedPropertiesEquals(expected, actual);
        assertContentPackageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContentPackageAllUpdatablePropertiesEquals(ContentPackage expected, ContentPackage actual) {
        assertContentPackageUpdatableFieldsEquals(expected, actual);
        assertContentPackageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContentPackageAutoGeneratedPropertiesEquals(ContentPackage expected, ContentPackage actual) {
        assertThat(actual)
            .as("Verify ContentPackage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContentPackageUpdatableFieldsEquals(ContentPackage expected, ContentPackage actual) {
        assertThat(actual)
            .as("Verify ContentPackage relevant properties")
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getVideoCount()).as("check videoCount").isEqualTo(expected.getVideoCount()))
            .satisfies(a -> assertThat(a.getImageCount()).as("check imageCount").isEqualTo(expected.getImageCount()))
            .satisfies(a -> assertThat(a.getIsPaidContent()).as("check isPaidContent").isEqualTo(expected.getIsPaidContent()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()))
            .satisfies(a -> assertThat(a.getMessageId()).as("check messageId").isEqualTo(expected.getMessageId()))
            .satisfies(a -> assertThat(a.getPostId()).as("check postId").isEqualTo(expected.getPostId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContentPackageUpdatableRelationshipsEquals(ContentPackage expected, ContentPackage actual) {
        // empty method
    }
}
