package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DirectMessageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDirectMessageAllPropertiesEquals(DirectMessage expected, DirectMessage actual) {
        assertDirectMessageAutoGeneratedPropertiesEquals(expected, actual);
        assertDirectMessageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDirectMessageAllUpdatablePropertiesEquals(DirectMessage expected, DirectMessage actual) {
        assertDirectMessageUpdatableFieldsEquals(expected, actual);
        assertDirectMessageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDirectMessageAutoGeneratedPropertiesEquals(DirectMessage expected, DirectMessage actual) {
        assertThat(actual)
            .as("Verify DirectMessage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDirectMessageUpdatableFieldsEquals(DirectMessage expected, DirectMessage actual) {
        assertThat(actual)
            .as("Verify DirectMessage relevant properties")
            .satisfies(a -> assertThat(a.getMessageContent()).as("check messageContent").isEqualTo(expected.getMessageContent()))
            .satisfies(a -> assertThat(a.getReadDate()).as("check readDate").isEqualTo(expected.getReadDate()))
            .satisfies(a -> assertThat(a.getLikeCount()).as("check likeCount").isEqualTo(expected.getLikeCount()))
            .satisfies(a -> assertThat(a.getIsHidden()).as("check isHidden").isEqualTo(expected.getIsHidden()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()))
            .satisfies(a -> assertThat(a.getRepliedStoryId()).as("check repliedStoryId").isEqualTo(expected.getRepliedStoryId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDirectMessageUpdatableRelationshipsEquals(DirectMessage expected, DirectMessage actual) {
        assertThat(actual)
            .as("Verify DirectMessage relationships")
            .satisfies(a -> assertThat(a.getResponseTo()).as("check responseTo").isEqualTo(expected.getResponseTo()))
            .satisfies(a -> assertThat(a.getChatRoom()).as("check chatRoom").isEqualTo(expected.getChatRoom()))
            .satisfies(a -> assertThat(a.getSender()).as("check sender").isEqualTo(expected.getSender()));
    }
}
