package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentReviewObservationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentReviewObservationAllPropertiesEquals(
        DocumentReviewObservation expected,
        DocumentReviewObservation actual
    ) {
        assertDocumentReviewObservationAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentReviewObservationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentReviewObservationAllUpdatablePropertiesEquals(
        DocumentReviewObservation expected,
        DocumentReviewObservation actual
    ) {
        assertDocumentReviewObservationUpdatableFieldsEquals(expected, actual);
        assertDocumentReviewObservationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentReviewObservationAutoGeneratedPropertiesEquals(
        DocumentReviewObservation expected,
        DocumentReviewObservation actual
    ) {
        assertThat(actual)
            .as("Verify DocumentReviewObservation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentReviewObservationUpdatableFieldsEquals(
        DocumentReviewObservation expected,
        DocumentReviewObservation actual
    ) {
        assertThat(actual)
            .as("Verify DocumentReviewObservation relevant properties")
            .satisfies(a -> assertThat(a.getCommentDate()).as("check commentDate").isEqualTo(expected.getCommentDate()))
            .satisfies(a -> assertThat(a.getComment()).as("check comment").isEqualTo(expected.getComment()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentReviewObservationUpdatableRelationshipsEquals(
        DocumentReviewObservation expected,
        DocumentReviewObservation actual
    ) {
        assertThat(actual)
            .as("Verify DocumentReviewObservation relationships")
            .satisfies(a -> assertThat(a.getReview()).as("check review").isEqualTo(expected.getReview()));
    }
}
