package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HashTagAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHashTagAllPropertiesEquals(HashTag expected, HashTag actual) {
        assertHashTagAutoGeneratedPropertiesEquals(expected, actual);
        assertHashTagAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHashTagAllUpdatablePropertiesEquals(HashTag expected, HashTag actual) {
        assertHashTagUpdatableFieldsEquals(expected, actual);
        assertHashTagUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHashTagAutoGeneratedPropertiesEquals(HashTag expected, HashTag actual) {
        assertThat(actual)
            .as("Verify HashTag auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHashTagUpdatableFieldsEquals(HashTag expected, HashTag actual) {
        assertThat(actual)
            .as("Verify HashTag relevant properties")
            .satisfies(a -> assertThat(a.getTagName()).as("check tagName").isEqualTo(expected.getTagName()))
            .satisfies(a -> assertThat(a.getHashtagType()).as("check hashtagType").isEqualTo(expected.getHashtagType()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHashTagUpdatableRelationshipsEquals(HashTag expected, HashTag actual) {
        // empty method
    }
}
