package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HelpSubcategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHelpSubcategoryAllPropertiesEquals(HelpSubcategory expected, HelpSubcategory actual) {
        assertHelpSubcategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertHelpSubcategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHelpSubcategoryAllUpdatablePropertiesEquals(HelpSubcategory expected, HelpSubcategory actual) {
        assertHelpSubcategoryUpdatableFieldsEquals(expected, actual);
        assertHelpSubcategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHelpSubcategoryAutoGeneratedPropertiesEquals(HelpSubcategory expected, HelpSubcategory actual) {
        assertThat(actual)
            .as("Verify HelpSubcategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHelpSubcategoryUpdatableFieldsEquals(HelpSubcategory expected, HelpSubcategory actual) {
        assertThat(actual)
            .as("Verify HelpSubcategory relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHelpSubcategoryUpdatableRelationshipsEquals(HelpSubcategory expected, HelpSubcategory actual) {
        assertThat(actual)
            .as("Verify HelpSubcategory relationships")
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()));
    }
}
