package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HelpRelatedArticleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHelpRelatedArticleAllPropertiesEquals(HelpRelatedArticle expected, HelpRelatedArticle actual) {
        assertHelpRelatedArticleAutoGeneratedPropertiesEquals(expected, actual);
        assertHelpRelatedArticleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHelpRelatedArticleAllUpdatablePropertiesEquals(HelpRelatedArticle expected, HelpRelatedArticle actual) {
        assertHelpRelatedArticleUpdatableFieldsEquals(expected, actual);
        assertHelpRelatedArticleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHelpRelatedArticleAutoGeneratedPropertiesEquals(HelpRelatedArticle expected, HelpRelatedArticle actual) {
        assertThat(actual)
            .as("Verify HelpRelatedArticle auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHelpRelatedArticleUpdatableFieldsEquals(HelpRelatedArticle expected, HelpRelatedArticle actual) {
        assertThat(actual)
            .as("Verify HelpRelatedArticle relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHelpRelatedArticleUpdatableRelationshipsEquals(HelpRelatedArticle expected, HelpRelatedArticle actual) {
        // empty method
    }
}
