package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HelpCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHelpCategoryAllPropertiesEquals(HelpCategory expected, HelpCategory actual) {
        assertHelpCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertHelpCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHelpCategoryAllUpdatablePropertiesEquals(HelpCategory expected, HelpCategory actual) {
        assertHelpCategoryUpdatableFieldsEquals(expected, actual);
        assertHelpCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHelpCategoryAutoGeneratedPropertiesEquals(HelpCategory expected, HelpCategory actual) {
        assertThat(actual)
            .as("Verify HelpCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHelpCategoryUpdatableFieldsEquals(HelpCategory expected, HelpCategory actual) {
        assertThat(actual)
            .as("Verify HelpCategory relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHelpCategoryUpdatableRelationshipsEquals(HelpCategory expected, HelpCategory actual) {
        // empty method
    }
}
