package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HelpQuestionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHelpQuestionAllPropertiesEquals(HelpQuestion expected, HelpQuestion actual) {
        assertHelpQuestionAutoGeneratedPropertiesEquals(expected, actual);
        assertHelpQuestionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHelpQuestionAllUpdatablePropertiesEquals(HelpQuestion expected, HelpQuestion actual) {
        assertHelpQuestionUpdatableFieldsEquals(expected, actual);
        assertHelpQuestionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHelpQuestionAutoGeneratedPropertiesEquals(HelpQuestion expected, HelpQuestion actual) {
        assertThat(actual)
            .as("Verify HelpQuestion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHelpQuestionUpdatableFieldsEquals(HelpQuestion expected, HelpQuestion actual) {
        assertThat(actual)
            .as("Verify HelpQuestion relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHelpQuestionUpdatableRelationshipsEquals(HelpQuestion expected, HelpQuestion actual) {
        assertThat(actual)
            .as("Verify HelpQuestion relationships")
            .satisfies(a -> assertThat(a.getSubcategory()).as("check subcategory").isEqualTo(expected.getSubcategory()));
    }
}
