package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IdentityDocumentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdentityDocumentAllPropertiesEquals(IdentityDocument expected, IdentityDocument actual) {
        assertIdentityDocumentAutoGeneratedPropertiesEquals(expected, actual);
        assertIdentityDocumentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdentityDocumentAllUpdatablePropertiesEquals(IdentityDocument expected, IdentityDocument actual) {
        assertIdentityDocumentUpdatableFieldsEquals(expected, actual);
        assertIdentityDocumentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdentityDocumentAutoGeneratedPropertiesEquals(IdentityDocument expected, IdentityDocument actual) {
        assertThat(actual)
            .as("Verify IdentityDocument auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdentityDocumentUpdatableFieldsEquals(IdentityDocument expected, IdentityDocument actual) {
        assertThat(actual)
            .as("Verify IdentityDocument relevant properties")
            .satisfies(a -> assertThat(a.getDocumentName()).as("check documentName").isEqualTo(expected.getDocumentName()))
            .satisfies(a ->
                assertThat(a.getDocumentDescription()).as("check documentDescription").isEqualTo(expected.getDocumentDescription())
            )
            .satisfies(a -> assertThat(a.getDocumentStatus()).as("check documentStatus").isEqualTo(expected.getDocumentStatus()))
            .satisfies(a -> assertThat(a.getDocumentType()).as("check documentType").isEqualTo(expected.getDocumentType()))
            .satisfies(a -> assertThat(a.getFileDocument()).as("check fileDocument").isEqualTo(expected.getFileDocument()))
            .satisfies(a ->
                assertThat(a.getFileDocumentContentType())
                    .as("check fileDocument contenty type")
                    .isEqualTo(expected.getFileDocumentContentType())
            )
            .satisfies(a -> assertThat(a.getFileDocumentS3Key()).as("check fileDocumentS3Key").isEqualTo(expected.getFileDocumentS3Key()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdentityDocumentUpdatableRelationshipsEquals(IdentityDocument expected, IdentityDocument actual) {
        assertThat(actual)
            .as("Verify IdentityDocument relationships")
            .satisfies(a -> assertThat(a.getReview()).as("check review").isEqualTo(expected.getReview()));
    }
}
