package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IdentityDocumentReviewAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdentityDocumentReviewAllPropertiesEquals(IdentityDocumentReview expected, IdentityDocumentReview actual) {
        assertIdentityDocumentReviewAutoGeneratedPropertiesEquals(expected, actual);
        assertIdentityDocumentReviewAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdentityDocumentReviewAllUpdatablePropertiesEquals(
        IdentityDocumentReview expected,
        IdentityDocumentReview actual
    ) {
        assertIdentityDocumentReviewUpdatableFieldsEquals(expected, actual);
        assertIdentityDocumentReviewUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdentityDocumentReviewAutoGeneratedPropertiesEquals(
        IdentityDocumentReview expected,
        IdentityDocumentReview actual
    ) {
        assertThat(actual)
            .as("Verify IdentityDocumentReview auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdentityDocumentReviewUpdatableFieldsEquals(IdentityDocumentReview expected, IdentityDocumentReview actual) {
        assertThat(actual)
            .as("Verify IdentityDocumentReview relevant properties")
            .satisfies(a -> assertThat(a.getDocumentStatus()).as("check documentStatus").isEqualTo(expected.getDocumentStatus()))
            .satisfies(a -> assertThat(a.getResolutionDate()).as("check resolutionDate").isEqualTo(expected.getResolutionDate()))
            .satisfies(a -> assertThat(a.getReviewStatus()).as("check reviewStatus").isEqualTo(expected.getReviewStatus()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getTicketId()).as("check ticketId").isEqualTo(expected.getTicketId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdentityDocumentReviewUpdatableRelationshipsEquals(
        IdentityDocumentReview expected,
        IdentityDocumentReview actual
    ) {
        // empty method
    }
}
