package com.monsterdam.app.domain;

import static com.monsterdam.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class LedgerEntryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLedgerEntryAllPropertiesEquals(LedgerEntry expected, LedgerEntry actual) {
        assertLedgerEntryAutoGeneratedPropertiesEquals(expected, actual);
        assertLedgerEntryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLedgerEntryAllUpdatablePropertiesEquals(LedgerEntry expected, LedgerEntry actual) {
        assertLedgerEntryUpdatableFieldsEquals(expected, actual);
        assertLedgerEntryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLedgerEntryAutoGeneratedPropertiesEquals(LedgerEntry expected, LedgerEntry actual) {
        assertThat(actual)
            .as("Verify LedgerEntry auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLedgerEntryUpdatableFieldsEquals(LedgerEntry expected, LedgerEntry actual) {
        assertThat(actual)
            .as("Verify LedgerEntry relevant properties")
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getEntryType()).as("check entryType").isEqualTo(expected.getEntryType()))
            .satisfies(a -> assertThat(a.getAccountType()).as("check accountType").isEqualTo(expected.getAccountType()))
            .satisfies(a -> assertThat(a.getAccountOwnerId()).as("check accountOwnerId").isEqualTo(expected.getAccountOwnerId()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a -> assertThat(a.getReferenceType()).as("check referenceType").isEqualTo(expected.getReferenceType()))
            .satisfies(a -> assertThat(a.getReferenceId()).as("check referenceId").isEqualTo(expected.getReferenceId()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLedgerEntryUpdatableRelationshipsEquals(LedgerEntry expected, LedgerEntry actual) {
        // empty method
    }
}
