package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LikeMarkAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLikeMarkAllPropertiesEquals(LikeMark expected, LikeMark actual) {
        assertLikeMarkAutoGeneratedPropertiesEquals(expected, actual);
        assertLikeMarkAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLikeMarkAllUpdatablePropertiesEquals(LikeMark expected, LikeMark actual) {
        assertLikeMarkUpdatableFieldsEquals(expected, actual);
        assertLikeMarkUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLikeMarkAutoGeneratedPropertiesEquals(LikeMark expected, LikeMark actual) {
        assertThat(actual)
            .as("Verify LikeMark auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLikeMarkUpdatableFieldsEquals(LikeMark expected, LikeMark actual) {
        assertThat(actual)
            .as("Verify LikeMark relevant properties")
            .satisfies(a -> assertThat(a.getEntityType()).as("check entityType").isEqualTo(expected.getEntityType()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()))
            .satisfies(a -> assertThat(a.getMultimediaId()).as("check multimediaId").isEqualTo(expected.getMultimediaId()))
            .satisfies(a -> assertThat(a.getMessageId()).as("check messageId").isEqualTo(expected.getMessageId()))
            .satisfies(a -> assertThat(a.getPostId()).as("check postId").isEqualTo(expected.getPostId()))
            .satisfies(a -> assertThat(a.getCommentId()).as("check commentId").isEqualTo(expected.getCommentId()))
            .satisfies(a -> assertThat(a.getLikerId()).as("check likerId").isEqualTo(expected.getLikerId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLikeMarkUpdatableRelationshipsEquals(LikeMark expected, LikeMark actual) {
        // empty method
    }
}
