package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ModerationActionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModerationActionAllPropertiesEquals(ModerationAction expected, ModerationAction actual) {
        assertModerationActionAutoGeneratedPropertiesEquals(expected, actual);
        assertModerationActionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModerationActionAllUpdatablePropertiesEquals(ModerationAction expected, ModerationAction actual) {
        assertModerationActionUpdatableFieldsEquals(expected, actual);
        assertModerationActionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModerationActionAutoGeneratedPropertiesEquals(ModerationAction expected, ModerationAction actual) {
        assertThat(actual)
            .as("Verify ModerationAction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModerationActionUpdatableFieldsEquals(ModerationAction expected, ModerationAction actual) {
        assertThat(actual)
            .as("Verify ModerationAction relevant properties")
            .satisfies(a -> assertThat(a.getActionType()).as("check actionType").isEqualTo(expected.getActionType()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a -> assertThat(a.getActionDate()).as("check actionDate").isEqualTo(expected.getActionDate()))
            .satisfies(a -> assertThat(a.getDurationDays()).as("check durationDays").isEqualTo(expected.getDurationDays()))
            .satisfies(a -> assertThat(a.getTicketId()).as("check ticketId").isEqualTo(expected.getTicketId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModerationActionUpdatableRelationshipsEquals(ModerationAction expected, ModerationAction actual) {
        // empty method
    }
}
