package com.monsterdam.app.domain;

import static com.monsterdam.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class MoneyWithdrawAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoneyWithdrawAllPropertiesEquals(MoneyWithdraw expected, MoneyWithdraw actual) {
        assertMoneyWithdrawAutoGeneratedPropertiesEquals(expected, actual);
        assertMoneyWithdrawAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoneyWithdrawAllUpdatablePropertiesEquals(MoneyWithdraw expected, MoneyWithdraw actual) {
        assertMoneyWithdrawUpdatableFieldsEquals(expected, actual);
        assertMoneyWithdrawUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoneyWithdrawAutoGeneratedPropertiesEquals(MoneyWithdraw expected, MoneyWithdraw actual) {
        assertThat(actual)
            .as("Verify MoneyWithdraw auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoneyWithdrawUpdatableFieldsEquals(MoneyWithdraw expected, MoneyWithdraw actual) {
        assertThat(actual)
            .as("Verify MoneyWithdraw relevant properties")
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getPayoutProviderName()).as("check payoutProviderName").isEqualTo(expected.getPayoutProviderName())
            )
            .satisfies(a -> assertThat(a.getPayoutReferenceId()).as("check payoutReferenceId").isEqualTo(expected.getPayoutReferenceId()))
            .satisfies(a -> assertThat(a.getProcessedAt()).as("check processedAt").isEqualTo(expected.getProcessedAt()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()))
            .satisfies(a -> assertThat(a.getWithdrawStatus()).as("check withdrawStatus").isEqualTo(expected.getWithdrawStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoneyWithdrawUpdatableRelationshipsEquals(MoneyWithdraw expected, MoneyWithdraw actual) {
        assertThat(actual)
            .as("Verify MoneyWithdraw relationships")
            .satisfies(a -> assertThat(a.getCreator()).as("check creator").isEqualTo(expected.getCreator()));
    }
}
