package com.monsterdam.app.domain;

import static com.monsterdam.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class MoneyEarningAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoneyEarningAllPropertiesEquals(MoneyEarning expected, MoneyEarning actual) {
        assertMoneyEarningAutoGeneratedPropertiesEquals(expected, actual);
        assertMoneyEarningAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoneyEarningAllUpdatablePropertiesEquals(MoneyEarning expected, MoneyEarning actual) {
        assertMoneyEarningUpdatableFieldsEquals(expected, actual);
        assertMoneyEarningUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoneyEarningAutoGeneratedPropertiesEquals(MoneyEarning expected, MoneyEarning actual) {
        assertThat(actual)
            .as("Verify MoneyEarning auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoneyEarningUpdatableFieldsEquals(MoneyEarning expected, MoneyEarning actual) {
        assertThat(actual)
            .as("Verify MoneyEarning relevant properties")
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()))
            .satisfies(a -> assertThat(a.getTransactionType()).as("check transactionType").isEqualTo(expected.getTransactionType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoneyEarningUpdatableRelationshipsEquals(MoneyEarning expected, MoneyEarning actual) {
        assertThat(actual)
            .as("Verify MoneyEarning relationships")
            .satisfies(a -> assertThat(a.getCreator()).as("check creator").isEqualTo(expected.getCreator()));
    }
}
