package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MoneyGiftAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoneyGiftAllPropertiesEquals(MoneyGift expected, MoneyGift actual) {
        assertMoneyGiftAutoGeneratedPropertiesEquals(expected, actual);
        assertMoneyGiftAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoneyGiftAllUpdatablePropertiesEquals(MoneyGift expected, MoneyGift actual) {
        assertMoneyGiftUpdatableFieldsEquals(expected, actual);
        assertMoneyGiftUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoneyGiftAutoGeneratedPropertiesEquals(MoneyGift expected, MoneyGift actual) {
        assertThat(actual)
            .as("Verify MoneyGift auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoneyGiftUpdatableFieldsEquals(MoneyGift expected, MoneyGift actual) {
        assertThat(actual)
            .as("Verify MoneyGift relevant properties")
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()))
            .satisfies(a -> assertThat(a.getMessageId()).as("check messageId").isEqualTo(expected.getMessageId()))
            .satisfies(a -> assertThat(a.getPostId()).as("check postId").isEqualTo(expected.getPostId()))
            .satisfies(a -> assertThat(a.getViewerId()).as("check viewerId").isEqualTo(expected.getViewerId()))
            .satisfies(a -> assertThat(a.getCreatorId()).as("check creatorId").isEqualTo(expected.getCreatorId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoneyGiftUpdatableRelationshipsEquals(MoneyGift expected, MoneyGift actual) {
        assertThat(actual)
            .as("Verify MoneyGift relationships")
            .satisfies(a -> assertThat(a.getPayment()).as("check payment").isEqualTo(expected.getPayment()));
    }
}
