package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PaymentProviderAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentProviderAllPropertiesEquals(PaymentProvider expected, PaymentProvider actual) {
        assertPaymentProviderAutoGeneratedPropertiesEquals(expected, actual);
        assertPaymentProviderAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentProviderAllUpdatablePropertiesEquals(PaymentProvider expected, PaymentProvider actual) {
        assertPaymentProviderUpdatableFieldsEquals(expected, actual);
        assertPaymentProviderUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentProviderAutoGeneratedPropertiesEquals(PaymentProvider expected, PaymentProvider actual) {
        assertThat(actual)
            .as("Verify PaymentProvider auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentProviderUpdatableFieldsEquals(PaymentProvider expected, PaymentProvider actual) {
        assertThat(actual)
            .as("Verify PaymentProvider relevant properties")
            .satisfies(a -> assertThat(a.getProviderName()).as("check providerName").isEqualTo(expected.getProviderName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getApiKeyText()).as("check apiKeyText").isEqualTo(expected.getApiKeyText()))
            .satisfies(a -> assertThat(a.getApiSecretText()).as("check apiSecretText").isEqualTo(expected.getApiSecretText()))
            .satisfies(a -> assertThat(a.getEndpointText()).as("check endpointText").isEqualTo(expected.getEndpointText()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentProviderUpdatableRelationshipsEquals(PaymentProvider expected, PaymentProvider actual) {
        // empty method
    }
}
