package com.monsterdam.app.domain;

import static com.monsterdam.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PaymentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentAllPropertiesEquals(Payment expected, Payment actual) {
        assertPaymentAutoGeneratedPropertiesEquals(expected, actual);
        assertPaymentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentAllUpdatablePropertiesEquals(Payment expected, Payment actual) {
        assertPaymentUpdatableFieldsEquals(expected, actual);
        assertPaymentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentAutoGeneratedPropertiesEquals(Payment expected, Payment actual) {
        assertThat(actual)
            .as("Verify Payment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentUpdatableFieldsEquals(Payment expected, Payment actual) {
        assertThat(actual)
            .as("Verify Payment relevant properties")
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getPaymentDate()).as("check paymentDate").isEqualTo(expected.getPaymentDate()))
            .satisfies(a -> assertThat(a.getPaymentStatus()).as("check paymentStatus").isEqualTo(expected.getPaymentStatus()))
            .satisfies(a -> assertThat(a.getPaymentReference()).as("check paymentReference").isEqualTo(expected.getPaymentReference()))
            .satisfies(a -> assertThat(a.getCloudTransactionId()).as("check cloudTransactionId").isEqualTo(expected.getCloudTransactionId())
            )
            .satisfies(a ->
                assertThat(a.getProviderPaymentIntentId())
                    .as("check providerPaymentIntentId")
                    .isEqualTo(expected.getProviderPaymentIntentId())
            )
            .satisfies(a -> assertThat(a.getProviderChargeId()).as("check providerChargeId").isEqualTo(expected.getProviderChargeId()))
            .satisfies(a -> assertThat(a.getProviderCustomerId()).as("check providerCustomerId").isEqualTo(expected.getProviderCustomerId())
            )
            .satisfies(a ->
                assertThat(a.getProviderPaymentMethodId())
                    .as("check providerPaymentMethodId")
                    .isEqualTo(expected.getProviderPaymentMethodId())
            )
            .satisfies(a ->
                assertThat(a.getProviderEventLastId()).as("check providerEventLastId").isEqualTo(expected.getProviderEventLastId())
            )
            .satisfies(a -> assertThat(a.getCountryCode()).as("check countryCode").isEqualTo(expected.getCountryCode()))
            .satisfies(a ->
                assertThat(a.getProviderFeeAmount())
                    .as("check providerFeeAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getProviderFeeAmount())
            )
            .satisfies(a ->
                assertThat(a.getPlatformFeeAmount())
                    .as("check platformFeeAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPlatformFeeAmount())
            )
            .satisfies(a ->
                assertThat(a.getCreatorNetAmount())
                    .as("check creatorNetAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCreatorNetAmount())
            )
            .satisfies(a ->
                assertThat(a.getTaxAmount()).as("check taxAmount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTaxAmount())
            )
            .satisfies(a -> assertThat(a.getAuthorizedDate()).as("check authorizedDate").isEqualTo(expected.getAuthorizedDate()))
            .satisfies(a -> assertThat(a.getCapturedDate()).as("check capturedDate").isEqualTo(expected.getCapturedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentUpdatableRelationshipsEquals(Payment expected, Payment actual) {
        assertThat(actual)
            .as("Verify Payment relationships")
            .satisfies(a -> assertThat(a.getMethod()).as("check method").isEqualTo(expected.getMethod()))
            .satisfies(a -> assertThat(a.getProvider()).as("check provider").isEqualTo(expected.getProvider()))
            .satisfies(a -> assertThat(a.getViewer()).as("check viewer").isEqualTo(expected.getViewer()));
    }
}
