package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PaymentProviderEventAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentProviderEventAllPropertiesEquals(PaymentProviderEvent expected, PaymentProviderEvent actual) {
        assertPaymentProviderEventAutoGeneratedPropertiesEquals(expected, actual);
        assertPaymentProviderEventAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentProviderEventAllUpdatablePropertiesEquals(PaymentProviderEvent expected, PaymentProviderEvent actual) {
        assertPaymentProviderEventUpdatableFieldsEquals(expected, actual);
        assertPaymentProviderEventUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentProviderEventAutoGeneratedPropertiesEquals(PaymentProviderEvent expected, PaymentProviderEvent actual) {
        assertThat(actual)
            .as("Verify PaymentProviderEvent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentProviderEventUpdatableFieldsEquals(PaymentProviderEvent expected, PaymentProviderEvent actual) {
        assertThat(actual)
            .as("Verify PaymentProviderEvent relevant properties")
            .satisfies(a -> assertThat(a.getProviderName()).as("check providerName").isEqualTo(expected.getProviderName()))
            .satisfies(a -> assertThat(a.getEventType()).as("check eventType").isEqualTo(expected.getEventType()))
            .satisfies(a -> assertThat(a.getEventId()).as("check eventId").isEqualTo(expected.getEventId()))
            .satisfies(a -> assertThat(a.getPayloadJson()).as("check payloadJson").isEqualTo(expected.getPayloadJson()))
            .satisfies(a -> assertThat(a.getReceivedAt()).as("check receivedAt").isEqualTo(expected.getReceivedAt()))
            .satisfies(a -> assertThat(a.getProcessedAt()).as("check processedAt").isEqualTo(expected.getProcessedAt()))
            .satisfies(a -> assertThat(a.getProcessingStatus()).as("check processingStatus").isEqualTo(expected.getProcessingStatus()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentProviderEventUpdatableRelationshipsEquals(PaymentProviderEvent expected, PaymentProviderEvent actual) {
        assertThat(actual)
            .as("Verify PaymentProviderEvent relationships")
            .satisfies(a -> assertThat(a.getPayment()).as("check payment").isEqualTo(expected.getPayment()));
    }
}
