package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PaymentMethodAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentMethodAllPropertiesEquals(PaymentMethod expected, PaymentMethod actual) {
        assertPaymentMethodAutoGeneratedPropertiesEquals(expected, actual);
        assertPaymentMethodAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentMethodAllUpdatablePropertiesEquals(PaymentMethod expected, PaymentMethod actual) {
        assertPaymentMethodUpdatableFieldsEquals(expected, actual);
        assertPaymentMethodUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentMethodAutoGeneratedPropertiesEquals(PaymentMethod expected, PaymentMethod actual) {
        assertThat(actual)
            .as("Verify PaymentMethod auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentMethodUpdatableFieldsEquals(PaymentMethod expected, PaymentMethod actual) {
        assertThat(actual)
            .as("Verify PaymentMethod relevant properties")
            .satisfies(a -> assertThat(a.getMethodName()).as("check methodName").isEqualTo(expected.getMethodName()))
            .satisfies(a -> assertThat(a.getTokenText()).as("check tokenText").isEqualTo(expected.getTokenText()))
            .satisfies(a -> assertThat(a.getExpirationDate()).as("check expirationDate").isEqualTo(expected.getExpirationDate()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentMethodUpdatableRelationshipsEquals(PaymentMethod expected, PaymentMethod actual) {
        // empty method
    }
}
