package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PersonalSocialLinksAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonalSocialLinksAllPropertiesEquals(PersonalSocialLinks expected, PersonalSocialLinks actual) {
        assertPersonalSocialLinksAutoGeneratedPropertiesEquals(expected, actual);
        assertPersonalSocialLinksAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonalSocialLinksAllUpdatablePropertiesEquals(PersonalSocialLinks expected, PersonalSocialLinks actual) {
        assertPersonalSocialLinksUpdatableFieldsEquals(expected, actual);
        assertPersonalSocialLinksUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonalSocialLinksAutoGeneratedPropertiesEquals(PersonalSocialLinks expected, PersonalSocialLinks actual) {
        assertThat(actual)
            .as("Verify PersonalSocialLinks auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonalSocialLinksUpdatableFieldsEquals(PersonalSocialLinks expected, PersonalSocialLinks actual) {
        assertThat(actual)
            .as("Verify PersonalSocialLinks relevant properties")
            .satisfies(a -> assertThat(a.getNormalImageS3Key()).as("check normalImageS3Key").isEqualTo(expected.getNormalImageS3Key()))
            .satisfies(a -> assertThat(a.getThumbnailIconS3Key()).as("check thumbnailIconS3Key").isEqualTo(expected.getThumbnailIconS3Key())
            )
            .satisfies(a -> assertThat(a.getSocialLink()).as("check socialLink").isEqualTo(expected.getSocialLink()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonalSocialLinksUpdatableRelationshipsEquals(PersonalSocialLinks expected, PersonalSocialLinks actual) {
        assertThat(actual)
            .as("Verify PersonalSocialLinks relationships")
            .satisfies(a -> assertThat(a.getSocialNetwork()).as("check socialNetwork").isEqualTo(expected.getSocialNetwork()))
            .satisfies(a -> assertThat(a.getUserProfile()).as("check userProfile").isEqualTo(expected.getUserProfile()));
    }
}
