package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PlatformAdminUserAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatformAdminUserAllPropertiesEquals(PlatformAdminUser expected, PlatformAdminUser actual) {
        assertPlatformAdminUserAutoGeneratedPropertiesEquals(expected, actual);
        assertPlatformAdminUserAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatformAdminUserAllUpdatablePropertiesEquals(PlatformAdminUser expected, PlatformAdminUser actual) {
        assertPlatformAdminUserUpdatableFieldsEquals(expected, actual);
        assertPlatformAdminUserUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatformAdminUserAutoGeneratedPropertiesEquals(PlatformAdminUser expected, PlatformAdminUser actual) {
        assertThat(actual)
            .as("Verify PlatformAdminUser auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatformAdminUserUpdatableFieldsEquals(PlatformAdminUser expected, PlatformAdminUser actual) {
        assertThat(actual)
            .as("Verify PlatformAdminUser relevant properties")
            .satisfies(a -> assertThat(a.getFullName()).as("check fullName").isEqualTo(expected.getFullName()))
            .satisfies(a -> assertThat(a.getEmailAddress()).as("check emailAddress").isEqualTo(expected.getEmailAddress()))
            .satisfies(a -> assertThat(a.getNickName()).as("check nickName").isEqualTo(expected.getNickName()))
            .satisfies(a -> assertThat(a.getGender()).as("check gender").isEqualTo(expected.getGender()))
            .satisfies(a -> assertThat(a.getMobilePhone()).as("check mobilePhone").isEqualTo(expected.getMobilePhone()))
            .satisfies(a -> assertThat(a.getLastLoginDate()).as("check lastLoginDate").isEqualTo(expected.getLastLoginDate()))
            .satisfies(a -> assertThat(a.getBirthDate()).as("check birthDate").isEqualTo(expected.getBirthDate()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatformAdminUserUpdatableRelationshipsEquals(PlatformAdminUser expected, PlatformAdminUser actual) {
        // empty method
    }
}
