package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PollOptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPollOptionAllPropertiesEquals(PollOption expected, PollOption actual) {
        assertPollOptionAutoGeneratedPropertiesEquals(expected, actual);
        assertPollOptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPollOptionAllUpdatablePropertiesEquals(PollOption expected, PollOption actual) {
        assertPollOptionUpdatableFieldsEquals(expected, actual);
        assertPollOptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPollOptionAutoGeneratedPropertiesEquals(PollOption expected, PollOption actual) {
        assertThat(actual)
            .as("Verify PollOption auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPollOptionUpdatableFieldsEquals(PollOption expected, PollOption actual) {
        assertThat(actual)
            .as("Verify PollOption relevant properties")
            .satisfies(a -> assertThat(a.getOptionDescription()).as("check optionDescription").isEqualTo(expected.getOptionDescription()))
            .satisfies(a -> assertThat(a.getVoteCount()).as("check voteCount").isEqualTo(expected.getVoteCount()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPollOptionUpdatableRelationshipsEquals(PollOption expected, PollOption actual) {
        assertThat(actual)
            .as("Verify PollOption relationships")
            .satisfies(a -> assertThat(a.getPoll()).as("check poll").isEqualTo(expected.getPoll()));
    }
}
