package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PollVoteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPollVoteAllPropertiesEquals(PollVote expected, PollVote actual) {
        assertPollVoteAutoGeneratedPropertiesEquals(expected, actual);
        assertPollVoteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPollVoteAllUpdatablePropertiesEquals(PollVote expected, PollVote actual) {
        assertPollVoteUpdatableFieldsEquals(expected, actual);
        assertPollVoteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPollVoteAutoGeneratedPropertiesEquals(PollVote expected, PollVote actual) {
        assertThat(actual)
            .as("Verify PollVote auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPollVoteUpdatableFieldsEquals(PollVote expected, PollVote actual) {
        assertThat(actual)
            .as("Verify PollVote relevant properties")
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getVotingUserId()).as("check votingUserId").isEqualTo(expected.getVotingUserId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPollVoteUpdatableRelationshipsEquals(PollVote expected, PollVote actual) {
        assertThat(actual)
            .as("Verify PollVote relationships")
            .satisfies(a -> assertThat(a.getPollOption()).as("check pollOption").isEqualTo(expected.getPollOption()));
    }
}
