package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PostFeedAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostFeedAllPropertiesEquals(PostFeed expected, PostFeed actual) {
        assertPostFeedAutoGeneratedPropertiesEquals(expected, actual);
        assertPostFeedAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostFeedAllUpdatablePropertiesEquals(PostFeed expected, PostFeed actual) {
        assertPostFeedUpdatableFieldsEquals(expected, actual);
        assertPostFeedUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostFeedAutoGeneratedPropertiesEquals(PostFeed expected, PostFeed actual) {
        assertThat(actual)
            .as("Verify PostFeed auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostFeedUpdatableFieldsEquals(PostFeed expected, PostFeed actual) {
        assertThat(actual)
            .as("Verify PostFeed relevant properties")
            .satisfies(a -> assertThat(a.getPostContent()).as("check postContent").isEqualTo(expected.getPostContent()))
            .satisfies(a -> assertThat(a.getIsPublic()).as("check isPublic").isEqualTo(expected.getIsPublic()))
            .satisfies(a -> assertThat(a.getPinnedPost()).as("check pinnedPost").isEqualTo(expected.getPinnedPost()))
            .satisfies(a -> assertThat(a.getLikeCount()).as("check likeCount").isEqualTo(expected.getLikeCount()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostFeedUpdatableRelationshipsEquals(PostFeed expected, PostFeed actual) {
        assertThat(actual)
            .as("Verify PostFeed relationships")
            .satisfies(a -> assertThat(a.getCreator()).as("check creator").isEqualTo(expected.getCreator()));
    }
}
