package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PostCommentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostCommentAllPropertiesEquals(PostComment expected, PostComment actual) {
        assertPostCommentAutoGeneratedPropertiesEquals(expected, actual);
        assertPostCommentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostCommentAllUpdatablePropertiesEquals(PostComment expected, PostComment actual) {
        assertPostCommentUpdatableFieldsEquals(expected, actual);
        assertPostCommentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostCommentAutoGeneratedPropertiesEquals(PostComment expected, PostComment actual) {
        assertThat(actual)
            .as("Verify PostComment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostCommentUpdatableFieldsEquals(PostComment expected, PostComment actual) {
        assertThat(actual)
            .as("Verify PostComment relevant properties")
            .satisfies(a -> assertThat(a.getCommentContent()).as("check commentContent").isEqualTo(expected.getCommentContent()))
            .satisfies(a -> assertThat(a.getLikeCount()).as("check likeCount").isEqualTo(expected.getLikeCount()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostCommentUpdatableRelationshipsEquals(PostComment expected, PostComment actual) {
        assertThat(actual)
            .as("Verify PostComment relationships")
            .satisfies(a -> assertThat(a.getPost()).as("check post").isEqualTo(expected.getPost()))
            .satisfies(a -> assertThat(a.getResponseTo()).as("check responseTo").isEqualTo(expected.getResponseTo()))
            .satisfies(a -> assertThat(a.getCommenter()).as("check commenter").isEqualTo(expected.getCommenter()));
    }
}
