package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PostMentionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostMentionAllPropertiesEquals(PostMention expected, PostMention actual) {
        assertPostMentionAutoGeneratedPropertiesEquals(expected, actual);
        assertPostMentionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostMentionAllUpdatablePropertiesEquals(PostMention expected, PostMention actual) {
        assertPostMentionUpdatableFieldsEquals(expected, actual);
        assertPostMentionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostMentionAutoGeneratedPropertiesEquals(PostMention expected, PostMention actual) {
        assertThat(actual)
            .as("Verify PostMention auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostMentionUpdatableFieldsEquals(PostMention expected, PostMention actual) {
        assertThat(actual)
            .as("Verify PostMention relevant properties")
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()))
            .satisfies(a -> assertThat(a.getMentionedUserId()).as("check mentionedUserId").isEqualTo(expected.getMentionedUserId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostMentionUpdatableRelationshipsEquals(PostMention expected, PostMention actual) {
        assertThat(actual)
            .as("Verify PostMention relationships")
            .satisfies(a -> assertThat(a.getOriginPost()).as("check originPost").isEqualTo(expected.getOriginPost()));
    }
}
