package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PostPollAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostPollAllPropertiesEquals(PostPoll expected, PostPoll actual) {
        assertPostPollAutoGeneratedPropertiesEquals(expected, actual);
        assertPostPollAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostPollAllUpdatablePropertiesEquals(PostPoll expected, PostPoll actual) {
        assertPostPollUpdatableFieldsEquals(expected, actual);
        assertPostPollUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostPollAutoGeneratedPropertiesEquals(PostPoll expected, PostPoll actual) {
        assertThat(actual)
            .as("Verify PostPoll auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostPollUpdatableFieldsEquals(PostPoll expected, PostPoll actual) {
        assertThat(actual)
            .as("Verify PostPoll relevant properties")
            .satisfies(a -> assertThat(a.getQuestion()).as("check question").isEqualTo(expected.getQuestion()))
            .satisfies(a -> assertThat(a.getIsMultiChoice()).as("check isMultiChoice").isEqualTo(expected.getIsMultiChoice()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getDuration()).as("check duration").isEqualTo(expected.getDuration()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostPollUpdatableRelationshipsEquals(PostPoll expected, PostPoll actual) {
        assertThat(actual)
            .as("Verify PostPoll relationships")
            .satisfies(a -> assertThat(a.getPost()).as("check post").isEqualTo(expected.getPost()));
    }
}
