package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PurchasedContentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchasedContentAllPropertiesEquals(PurchasedContent expected, PurchasedContent actual) {
        assertPurchasedContentAutoGeneratedPropertiesEquals(expected, actual);
        assertPurchasedContentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchasedContentAllUpdatablePropertiesEquals(PurchasedContent expected, PurchasedContent actual) {
        assertPurchasedContentUpdatableFieldsEquals(expected, actual);
        assertPurchasedContentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchasedContentAutoGeneratedPropertiesEquals(PurchasedContent expected, PurchasedContent actual) {
        assertThat(actual)
            .as("Verify PurchasedContent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchasedContentUpdatableFieldsEquals(PurchasedContent expected, PurchasedContent actual) {
        assertThat(actual)
            .as("Verify PurchasedContent relevant properties")
            .satisfies(a -> assertThat(a.getRating()).as("check rating").isEqualTo(expected.getRating()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()))
            .satisfies(a -> assertThat(a.getViewerId()).as("check viewerId").isEqualTo(expected.getViewerId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchasedContentUpdatableRelationshipsEquals(PurchasedContent expected, PurchasedContent actual) {
        assertThat(actual)
            .as("Verify PurchasedContent relationships")
            .satisfies(a -> assertThat(a.getPayment()).as("check payment").isEqualTo(expected.getPayment()));
    }
}
