package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PurchasedSubscriptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchasedSubscriptionAllPropertiesEquals(PurchasedSubscription expected, PurchasedSubscription actual) {
        assertPurchasedSubscriptionAutoGeneratedPropertiesEquals(expected, actual);
        assertPurchasedSubscriptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchasedSubscriptionAllUpdatablePropertiesEquals(
        PurchasedSubscription expected,
        PurchasedSubscription actual
    ) {
        assertPurchasedSubscriptionUpdatableFieldsEquals(expected, actual);
        assertPurchasedSubscriptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchasedSubscriptionAutoGeneratedPropertiesEquals(
        PurchasedSubscription expected,
        PurchasedSubscription actual
    ) {
        assertThat(actual)
            .as("Verify PurchasedSubscription auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchasedSubscriptionUpdatableFieldsEquals(PurchasedSubscription expected, PurchasedSubscription actual) {
        assertThat(actual)
            .as("Verify PurchasedSubscription relevant properties")
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getSubscriptionStatus()).as("check subscriptionStatus").isEqualTo(expected.getSubscriptionStatus())
            )
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchasedSubscriptionUpdatableRelationshipsEquals(
        PurchasedSubscription expected,
        PurchasedSubscription actual
    ) {
        assertThat(actual)
            .as("Verify PurchasedSubscription relationships")
            .satisfies(a -> assertThat(a.getViewer()).as("check viewer").isEqualTo(expected.getViewer()))
            .satisfies(a -> assertThat(a.getCreator()).as("check creator").isEqualTo(expected.getCreator()))
            .satisfies(a -> assertThat(a.getPayment()).as("check payment").isEqualTo(expected.getPayment()))
            .satisfies(a ->
                assertThat(a.getSubscriptionPlanOffer()).as("check subscriptionPlanOffer").isEqualTo(expected.getSubscriptionPlanOffer())
            );
    }
}
