package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SinglePhotoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSinglePhotoAllPropertiesEquals(SinglePhoto expected, SinglePhoto actual) {
        assertSinglePhotoAutoGeneratedPropertiesEquals(expected, actual);
        assertSinglePhotoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSinglePhotoAllUpdatablePropertiesEquals(SinglePhoto expected, SinglePhoto actual) {
        assertSinglePhotoUpdatableFieldsEquals(expected, actual);
        assertSinglePhotoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSinglePhotoAutoGeneratedPropertiesEquals(SinglePhoto expected, SinglePhoto actual) {
        assertThat(actual)
            .as("Verify SinglePhoto auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSinglePhotoUpdatableFieldsEquals(SinglePhoto expected, SinglePhoto actual) {
        assertThat(actual)
            .as("Verify SinglePhoto relevant properties")
            .satisfies(a -> assertThat(a.getThumbnail()).as("check thumbnail").isEqualTo(expected.getThumbnail()))
            .satisfies(a ->
                assertThat(a.getThumbnailContentType()).as("check thumbnail contenty type").isEqualTo(expected.getThumbnailContentType())
            )
            .satisfies(a -> assertThat(a.getThumbnailS3Key()).as("check thumbnailS3Key").isEqualTo(expected.getThumbnailS3Key()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a ->
                assertThat(a.getContentContentType()).as("check content contenty type").isEqualTo(expected.getContentContentType())
            )
            .satisfies(a -> assertThat(a.getContentS3Key()).as("check contentS3Key").isEqualTo(expected.getContentS3Key()))
            .satisfies(a -> assertThat(a.getLikeCount()).as("check likeCount").isEqualTo(expected.getLikeCount()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSinglePhotoUpdatableRelationshipsEquals(SinglePhoto expected, SinglePhoto actual) {
        assertThat(actual)
            .as("Verify SinglePhoto relationships")
            .satisfies(a -> assertThat(a.getContentPackage()).as("check contentPackage").isEqualTo(expected.getContentPackage()))
            .satisfies(a -> assertThat(a.getCreator()).as("check creator").isEqualTo(expected.getCreator()));
    }
}
