package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SingleVideoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSingleVideoAllPropertiesEquals(SingleVideo expected, SingleVideo actual) {
        assertSingleVideoAutoGeneratedPropertiesEquals(expected, actual);
        assertSingleVideoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSingleVideoAllUpdatablePropertiesEquals(SingleVideo expected, SingleVideo actual) {
        assertSingleVideoUpdatableFieldsEquals(expected, actual);
        assertSingleVideoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSingleVideoAutoGeneratedPropertiesEquals(SingleVideo expected, SingleVideo actual) {
        assertThat(actual)
            .as("Verify SingleVideo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSingleVideoUpdatableFieldsEquals(SingleVideo expected, SingleVideo actual) {
        assertThat(actual)
            .as("Verify SingleVideo relevant properties")
            .satisfies(a -> assertThat(a.getThumbnailS3Key()).as("check thumbnailS3Key").isEqualTo(expected.getThumbnailS3Key()))
            .satisfies(a -> assertThat(a.getContentS3Key()).as("check contentS3Key").isEqualTo(expected.getContentS3Key()))
            .satisfies(a -> assertThat(a.getDuration()).as("check duration").isEqualTo(expected.getDuration()))
            .satisfies(a -> assertThat(a.getLikeCount()).as("check likeCount").isEqualTo(expected.getLikeCount()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()))
            .satisfies(a -> assertThat(a.getCreatorId()).as("check creatorId").isEqualTo(expected.getCreatorId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSingleVideoUpdatableRelationshipsEquals(SingleVideo expected, SingleVideo actual) {
        assertThat(actual)
            .as("Verify SingleVideo relationships")
            .satisfies(a -> assertThat(a.getContentPackage()).as("check contentPackage").isEqualTo(expected.getContentPackage()));
    }
}
