package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SingleAudioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSingleAudioAllPropertiesEquals(SingleAudio expected, SingleAudio actual) {
        assertSingleAudioAutoGeneratedPropertiesEquals(expected, actual);
        assertSingleAudioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSingleAudioAllUpdatablePropertiesEquals(SingleAudio expected, SingleAudio actual) {
        assertSingleAudioUpdatableFieldsEquals(expected, actual);
        assertSingleAudioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSingleAudioAutoGeneratedPropertiesEquals(SingleAudio expected, SingleAudio actual) {
        assertThat(actual)
            .as("Verify SingleAudio auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSingleAudioUpdatableFieldsEquals(SingleAudio expected, SingleAudio actual) {
        assertThat(actual)
            .as("Verify SingleAudio relevant properties")
            .satisfies(a -> assertThat(a.getThumbnail()).as("check thumbnail").isEqualTo(expected.getThumbnail()))
            .satisfies(a ->
                assertThat(a.getThumbnailContentType()).as("check thumbnail contenty type").isEqualTo(expected.getThumbnailContentType())
            )
            .satisfies(a -> assertThat(a.getThumbnailS3Key()).as("check thumbnailS3Key").isEqualTo(expected.getThumbnailS3Key()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a ->
                assertThat(a.getContentContentType()).as("check content contenty type").isEqualTo(expected.getContentContentType())
            )
            .satisfies(a -> assertThat(a.getContentS3Key()).as("check contentS3Key").isEqualTo(expected.getContentS3Key()))
            .satisfies(a -> assertThat(a.getDuration()).as("check duration").isEqualTo(expected.getDuration()))
            .satisfies(a -> assertThat(a.getIsPreview()).as("check isPreview").isEqualTo(expected.getIsPreview()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSingleAudioUpdatableRelationshipsEquals(SingleAudio expected, SingleAudio actual) {
        assertThat(actual)
            .as("Verify SingleAudio relationships")
            .satisfies(a -> assertThat(a.getContentPackage()).as("check contentPackage").isEqualTo(expected.getContentPackage()))
            .satisfies(a -> assertThat(a.getCreator()).as("check creator").isEqualTo(expected.getCreator()));
    }
}
