package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SocialNetworkAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSocialNetworkAllPropertiesEquals(SocialNetwork expected, SocialNetwork actual) {
        assertSocialNetworkAutoGeneratedPropertiesEquals(expected, actual);
        assertSocialNetworkAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSocialNetworkAllUpdatablePropertiesEquals(SocialNetwork expected, SocialNetwork actual) {
        assertSocialNetworkUpdatableFieldsEquals(expected, actual);
        assertSocialNetworkUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSocialNetworkAutoGeneratedPropertiesEquals(SocialNetwork expected, SocialNetwork actual) {
        assertThat(actual)
            .as("Verify SocialNetwork auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSocialNetworkUpdatableFieldsEquals(SocialNetwork expected, SocialNetwork actual) {
        assertThat(actual)
            .as("Verify SocialNetwork relevant properties")
            .satisfies(a -> assertThat(a.getThumbnail()).as("check thumbnail").isEqualTo(expected.getThumbnail()))
            .satisfies(a ->
                assertThat(a.getThumbnailContentType()).as("check thumbnail contenty type").isEqualTo(expected.getThumbnailContentType())
            )
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCompleteName()).as("check completeName").isEqualTo(expected.getCompleteName()))
            .satisfies(a -> assertThat(a.getMainLink()).as("check mainLink").isEqualTo(expected.getMainLink()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSocialNetworkUpdatableRelationshipsEquals(SocialNetwork expected, SocialNetwork actual) {
        // empty method
    }
}
