package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SpecialAwardAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSpecialAwardAllPropertiesEquals(SpecialAward expected, SpecialAward actual) {
        assertSpecialAwardAutoGeneratedPropertiesEquals(expected, actual);
        assertSpecialAwardAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSpecialAwardAllUpdatablePropertiesEquals(SpecialAward expected, SpecialAward actual) {
        assertSpecialAwardUpdatableFieldsEquals(expected, actual);
        assertSpecialAwardUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSpecialAwardAutoGeneratedPropertiesEquals(SpecialAward expected, SpecialAward actual) {
        assertThat(actual)
            .as("Verify SpecialAward auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSpecialAwardUpdatableFieldsEquals(SpecialAward expected, SpecialAward actual) {
        assertThat(actual)
            .as("Verify SpecialAward relevant properties")
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a -> assertThat(a.getAltSpecialTitle()).as("check altSpecialTitle").isEqualTo(expected.getAltSpecialTitle()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()))
            .satisfies(a -> assertThat(a.getSpecialTitleId()).as("check specialTitleId").isEqualTo(expected.getSpecialTitleId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSpecialAwardUpdatableRelationshipsEquals(SpecialAward expected, SpecialAward actual) {
        assertThat(actual)
            .as("Verify SpecialAward relationships")
            .satisfies(a -> assertThat(a.getCreator()).as("check creator").isEqualTo(expected.getCreator()))
            .satisfies(a -> assertThat(a.getViewer()).as("check viewer").isEqualTo(expected.getViewer()));
    }
}
