package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStateAllPropertiesEquals(State expected, State actual) {
        assertStateAutoGeneratedPropertiesEquals(expected, actual);
        assertStateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStateAllUpdatablePropertiesEquals(State expected, State actual) {
        assertStateUpdatableFieldsEquals(expected, actual);
        assertStateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStateAutoGeneratedPropertiesEquals(State expected, State actual) {
        assertThat(actual)
            .as("Verify State auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStateUpdatableFieldsEquals(State expected, State actual) {
        assertThat(actual)
            .as("Verify State relevant properties")
            .satisfies(a -> assertThat(a.getStateName()).as("check stateName").isEqualTo(expected.getStateName()))
            .satisfies(a -> assertThat(a.getIsoCode()).as("check isoCode").isEqualTo(expected.getIsoCode()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()))
            .satisfies(a -> assertThat(a.getCountryId()).as("check countryId").isEqualTo(expected.getCountryId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStateUpdatableRelationshipsEquals(State expected, State actual) {
        // empty method
    }
}
