package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StateUserRelationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStateUserRelationAllPropertiesEquals(StateUserRelation expected, StateUserRelation actual) {
        assertStateUserRelationAutoGeneratedPropertiesEquals(expected, actual);
        assertStateUserRelationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStateUserRelationAllUpdatablePropertiesEquals(StateUserRelation expected, StateUserRelation actual) {
        assertStateUserRelationUpdatableFieldsEquals(expected, actual);
        assertStateUserRelationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStateUserRelationAutoGeneratedPropertiesEquals(StateUserRelation expected, StateUserRelation actual) {
        assertThat(actual)
            .as("Verify StateUserRelation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStateUserRelationUpdatableFieldsEquals(StateUserRelation expected, StateUserRelation actual) {
        assertThat(actual)
            .as("Verify StateUserRelation relevant properties")
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStateUserRelationUpdatableRelationshipsEquals(StateUserRelation expected, StateUserRelation actual) {
        assertThat(actual)
            .as("Verify StateUserRelation relationships")
            .satisfies(a -> assertThat(a.getState()).as("check state").isEqualTo(expected.getState()))
            .satisfies(a -> assertThat(a.getUserProfile()).as("check userProfile").isEqualTo(expected.getUserProfile()));
    }
}
