package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SubscriptionPlanOfferAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscriptionPlanOfferAllPropertiesEquals(SubscriptionPlanOffer expected, SubscriptionPlanOffer actual) {
        assertSubscriptionPlanOfferAutoGeneratedPropertiesEquals(expected, actual);
        assertSubscriptionPlanOfferAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscriptionPlanOfferAllUpdatablePropertiesEquals(
        SubscriptionPlanOffer expected,
        SubscriptionPlanOffer actual
    ) {
        assertSubscriptionPlanOfferUpdatableFieldsEquals(expected, actual);
        assertSubscriptionPlanOfferUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscriptionPlanOfferAutoGeneratedPropertiesEquals(
        SubscriptionPlanOffer expected,
        SubscriptionPlanOffer actual
    ) {
        assertThat(actual)
            .as("Verify SubscriptionPlanOffer auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscriptionPlanOfferUpdatableFieldsEquals(SubscriptionPlanOffer expected, SubscriptionPlanOffer actual) {
        assertThat(actual)
            .as("Verify SubscriptionPlanOffer relevant properties")
            .satisfies(a -> assertThat(a.getFreeDaysDuration()).as("check freeDaysDuration").isEqualTo(expected.getFreeDaysDuration()))
            .satisfies(a -> assertThat(a.getDiscountPercentage()).as("check discountPercentage").isEqualTo(expected.getDiscountPercentage())
            )
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getSubscriptionsLimit()).as("check subscriptionsLimit").isEqualTo(expected.getSubscriptionsLimit())
            )
            .satisfies(a -> assertThat(a.getPromotionType()).as("check promotionType").isEqualTo(expected.getPromotionType()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscriptionPlanOfferUpdatableRelationshipsEquals(
        SubscriptionPlanOffer expected,
        SubscriptionPlanOffer actual
    ) {
        assertThat(actual)
            .as("Verify SubscriptionPlanOffer relationships")
            .satisfies(a -> assertThat(a.getCreator()).as("check creator").isEqualTo(expected.getCreator()));
    }
}
