package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TaxInfoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaxInfoAllPropertiesEquals(TaxInfo expected, TaxInfo actual) {
        assertTaxInfoAutoGeneratedPropertiesEquals(expected, actual);
        assertTaxInfoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaxInfoAllUpdatablePropertiesEquals(TaxInfo expected, TaxInfo actual) {
        assertTaxInfoUpdatableFieldsEquals(expected, actual);
        assertTaxInfoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaxInfoAutoGeneratedPropertiesEquals(TaxInfo expected, TaxInfo actual) {
        assertThat(actual)
            .as("Verify TaxInfo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaxInfoUpdatableFieldsEquals(TaxInfo expected, TaxInfo actual) {
        assertThat(actual)
            .as("Verify TaxInfo relevant properties")
            .satisfies(a -> assertThat(a.getRatePercentage()).as("check ratePercentage").isEqualTo(expected.getRatePercentage()))
            .satisfies(a -> assertThat(a.getTaxType()).as("check taxType").isEqualTo(expected.getTaxType()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaxInfoUpdatableRelationshipsEquals(TaxInfo expected, TaxInfo actual) {
        assertThat(actual)
            .as("Verify TaxInfo relationships")
            .satisfies(a -> assertThat(a.getCountry()).as("check country").isEqualTo(expected.getCountry()));
    }
}
