package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TrialLinkAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrialLinkAllPropertiesEquals(TrialLink expected, TrialLink actual) {
        assertTrialLinkAutoGeneratedPropertiesEquals(expected, actual);
        assertTrialLinkAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrialLinkAllUpdatablePropertiesEquals(TrialLink expected, TrialLink actual) {
        assertTrialLinkUpdatableFieldsEquals(expected, actual);
        assertTrialLinkUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrialLinkAutoGeneratedPropertiesEquals(TrialLink expected, TrialLink actual) {
        assertThat(actual)
            .as("Verify TrialLink auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrialLinkUpdatableFieldsEquals(TrialLink expected, TrialLink actual) {
        assertThat(actual)
            .as("Verify TrialLink relevant properties")
            .satisfies(a -> assertThat(a.getLinkCode()).as("check linkCode").isEqualTo(expected.getLinkCode()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getFreeDays()).as("check freeDays").isEqualTo(expected.getFreeDays()))
            .satisfies(a -> assertThat(a.getIsUsed()).as("check isUsed").isEqualTo(expected.getIsUsed()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrialLinkUpdatableRelationshipsEquals(TrialLink expected, TrialLink actual) {
        assertThat(actual)
            .as("Verify TrialLink relationships")
            .satisfies(a -> assertThat(a.getCreator()).as("check creator").isEqualTo(expected.getCreator()));
    }
}
