package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserReportAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserReportAllPropertiesEquals(UserReport expected, UserReport actual) {
        assertUserReportAutoGeneratedPropertiesEquals(expected, actual);
        assertUserReportAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserReportAllUpdatablePropertiesEquals(UserReport expected, UserReport actual) {
        assertUserReportUpdatableFieldsEquals(expected, actual);
        assertUserReportUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserReportAutoGeneratedPropertiesEquals(UserReport expected, UserReport actual) {
        assertThat(actual)
            .as("Verify UserReport auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserReportUpdatableFieldsEquals(UserReport expected, UserReport actual) {
        assertThat(actual)
            .as("Verify UserReport relevant properties")
            .satisfies(a -> assertThat(a.getReportDescription()).as("check reportDescription").isEqualTo(expected.getReportDescription()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()))
            .satisfies(a -> assertThat(a.getReportCategory()).as("check reportCategory").isEqualTo(expected.getReportCategory()))
            .satisfies(a -> assertThat(a.getReporterId()).as("check reporterId").isEqualTo(expected.getReporterId()))
            .satisfies(a -> assertThat(a.getReportedId()).as("check reportedId").isEqualTo(expected.getReportedId()))
            .satisfies(a -> assertThat(a.getMultimediaId()).as("check multimediaId").isEqualTo(expected.getMultimediaId()))
            .satisfies(a -> assertThat(a.getMessageId()).as("check messageId").isEqualTo(expected.getMessageId()))
            .satisfies(a -> assertThat(a.getPostId()).as("check postId").isEqualTo(expected.getPostId()))
            .satisfies(a -> assertThat(a.getCommentId()).as("check commentId").isEqualTo(expected.getCommentId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserReportUpdatableRelationshipsEquals(UserReport expected, UserReport actual) {
        assertThat(actual)
            .as("Verify UserReport relationships")
            .satisfies(a -> assertThat(a.getTicket()).as("check ticket").isEqualTo(expected.getTicket()));
    }
}
