package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserSettingsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSettingsAllPropertiesEquals(UserSettings expected, UserSettings actual) {
        assertUserSettingsAutoGeneratedPropertiesEquals(expected, actual);
        assertUserSettingsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSettingsAllUpdatablePropertiesEquals(UserSettings expected, UserSettings actual) {
        assertUserSettingsUpdatableFieldsEquals(expected, actual);
        assertUserSettingsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSettingsAutoGeneratedPropertiesEquals(UserSettings expected, UserSettings actual) {
        assertThat(actual)
            .as("Verify UserSettings auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSettingsUpdatableFieldsEquals(UserSettings expected, UserSettings actual) {
        assertThat(actual)
            .as("Verify UserSettings relevant properties")
            .satisfies(a -> assertThat(a.getDarkMode()).as("check darkMode").isEqualTo(expected.getDarkMode()))
            .satisfies(a -> assertThat(a.getLanguage()).as("check language").isEqualTo(expected.getLanguage()))
            .satisfies(a -> assertThat(a.getContentFilter()).as("check contentFilter").isEqualTo(expected.getContentFilter()))
            .satisfies(a ->
                assertThat(a.getMessageBlurIntensity()).as("check messageBlurIntensity").isEqualTo(expected.getMessageBlurIntensity())
            )
            .satisfies(a ->
                assertThat(a.getActivityStatusVisibility())
                    .as("check activityStatusVisibility")
                    .isEqualTo(expected.getActivityStatusVisibility())
            )
            .satisfies(a ->
                assertThat(a.getTwoFactorAuthentication())
                    .as("check twoFactorAuthentication")
                    .isEqualTo(expected.getTwoFactorAuthentication())
            )
            .satisfies(a ->
                assertThat(a.getSessionsActiveCount()).as("check sessionsActiveCount").isEqualTo(expected.getSessionsActiveCount())
            )
            .satisfies(a -> assertThat(a.getEmailNotifications()).as("check emailNotifications").isEqualTo(expected.getEmailNotifications())
            )
            .satisfies(a ->
                assertThat(a.getImportantSubscriptionNotifications())
                    .as("check importantSubscriptionNotifications")
                    .isEqualTo(expected.getImportantSubscriptionNotifications())
            )
            .satisfies(a -> assertThat(a.getNewMessages()).as("check newMessages").isEqualTo(expected.getNewMessages()))
            .satisfies(a -> assertThat(a.getPostReplies()).as("check postReplies").isEqualTo(expected.getPostReplies()))
            .satisfies(a -> assertThat(a.getPostLikes()).as("check postLikes").isEqualTo(expected.getPostLikes()))
            .satisfies(a -> assertThat(a.getNewFollowers()).as("check newFollowers").isEqualTo(expected.getNewFollowers()))
            .satisfies(a -> assertThat(a.getSmsNewStream()).as("check smsNewStream").isEqualTo(expected.getSmsNewStream()))
            .satisfies(a -> assertThat(a.getToastNewComment()).as("check toastNewComment").isEqualTo(expected.getToastNewComment()))
            .satisfies(a -> assertThat(a.getToastNewLikes()).as("check toastNewLikes").isEqualTo(expected.getToastNewLikes()))
            .satisfies(a -> assertThat(a.getToastNewStream()).as("check toastNewStream").isEqualTo(expected.getToastNewStream()))
            .satisfies(a -> assertThat(a.getSiteNewComment()).as("check siteNewComment").isEqualTo(expected.getSiteNewComment()))
            .satisfies(a -> assertThat(a.getSiteNewLikes()).as("check siteNewLikes").isEqualTo(expected.getSiteNewLikes()))
            .satisfies(a ->
                assertThat(a.getSiteDiscountsFromFollowedUsers())
                    .as("check siteDiscountsFromFollowedUsers")
                    .isEqualTo(expected.getSiteDiscountsFromFollowedUsers())
            )
            .satisfies(a -> assertThat(a.getSiteNewStream()).as("check siteNewStream").isEqualTo(expected.getSiteNewStream()))
            .satisfies(a ->
                assertThat(a.getSiteUpcomingStreamReminders())
                    .as("check siteUpcomingStreamReminders")
                    .isEqualTo(expected.getSiteUpcomingStreamReminders())
            )
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSettingsUpdatableRelationshipsEquals(UserSettings expected, UserSettings actual) {
        // empty method
    }
}
