package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserAssociationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserAssociationAllPropertiesEquals(UserAssociation expected, UserAssociation actual) {
        assertUserAssociationAutoGeneratedPropertiesEquals(expected, actual);
        assertUserAssociationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserAssociationAllUpdatablePropertiesEquals(UserAssociation expected, UserAssociation actual) {
        assertUserAssociationUpdatableFieldsEquals(expected, actual);
        assertUserAssociationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserAssociationAutoGeneratedPropertiesEquals(UserAssociation expected, UserAssociation actual) {
        assertThat(actual)
            .as("Verify UserAssociation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserAssociationUpdatableFieldsEquals(UserAssociation expected, UserAssociation actual) {
        assertThat(actual)
            .as("Verify UserAssociation relevant properties")
            .satisfies(a -> assertThat(a.getRequestedDate()).as("check requestedDate").isEqualTo(expected.getRequestedDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getAssociationToken()).as("check associationToken").isEqualTo(expected.getAssociationToken()))
            .satisfies(a -> assertThat(a.getExpiryDate()).as("check expiryDate").isEqualTo(expected.getExpiryDate()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserAssociationUpdatableRelationshipsEquals(UserAssociation expected, UserAssociation actual) {
        assertThat(actual)
            .as("Verify UserAssociation relationships")
            .satisfies(a -> assertThat(a.getOwner()).as("check owner").isEqualTo(expected.getOwner()));
    }
}
