package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserLiteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserLiteAllPropertiesEquals(UserLite expected, UserLite actual) {
        assertUserLiteAutoGeneratedPropertiesEquals(expected, actual);
        assertUserLiteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserLiteAllUpdatablePropertiesEquals(UserLite expected, UserLite actual) {
        assertUserLiteUpdatableFieldsEquals(expected, actual);
        assertUserLiteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserLiteAutoGeneratedPropertiesEquals(UserLite expected, UserLite actual) {
        assertThat(actual)
            .as("Verify UserLite auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserLiteUpdatableFieldsEquals(UserLite expected, UserLite actual) {
        assertThat(actual)
            .as("Verify UserLite relevant properties")
            .satisfies(a -> assertThat(a.getThumbnailS3Key()).as("check thumbnailS3Key").isEqualTo(expected.getThumbnailS3Key()))
            .satisfies(a -> assertThat(a.getBirthDate()).as("check birthDate").isEqualTo(expected.getBirthDate()))
            .satisfies(a -> assertThat(a.getGender()).as("check gender").isEqualTo(expected.getGender()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()))
            .satisfies(a -> assertThat(a.getNickName()).as("check nickName").isEqualTo(expected.getNickName()))
            .satisfies(a -> assertThat(a.getFullName()).as("check fullName").isEqualTo(expected.getFullName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserLiteUpdatableRelationshipsEquals(UserLite expected, UserLite actual) {
        assertThat(actual)
            .as("Verify UserLite relationships")
            .satisfies(a -> assertThat(a.getProfile()).as("check profile").isEqualTo(expected.getProfile()))
            .satisfies(a -> assertThat(a.getSettings()).as("check settings").isEqualTo(expected.getSettings()))
            .satisfies(a -> assertThat(a.getCountryOfBirth()).as("check countryOfBirth").isEqualTo(expected.getCountryOfBirth()));
    }
}
