package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserProfileAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserProfileAllPropertiesEquals(UserProfile expected, UserProfile actual) {
        assertUserProfileAutoGeneratedPropertiesEquals(expected, actual);
        assertUserProfileAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserProfileAllUpdatablePropertiesEquals(UserProfile expected, UserProfile actual) {
        assertUserProfileUpdatableFieldsEquals(expected, actual);
        assertUserProfileUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserProfileAutoGeneratedPropertiesEquals(UserProfile expected, UserProfile actual) {
        assertThat(actual)
            .as("Verify UserProfile auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserProfileUpdatableFieldsEquals(UserProfile expected, UserProfile actual) {
        assertThat(actual)
            .as("Verify UserProfile relevant properties")
            .satisfies(a -> assertThat(a.getEmailContact()).as("check emailContact").isEqualTo(expected.getEmailContact()))
            .satisfies(a -> assertThat(a.getProfilePhotoS3Key()).as("check profilePhotoS3Key").isEqualTo(expected.getProfilePhotoS3Key()))
            .satisfies(a -> assertThat(a.getCoverPhotoS3Key()).as("check coverPhotoS3Key").isEqualTo(expected.getCoverPhotoS3Key()))
            .satisfies(a -> assertThat(a.getMainContentUrl()).as("check mainContentUrl").isEqualTo(expected.getMainContentUrl()))
            .satisfies(a -> assertThat(a.getMobilePhone()).as("check mobilePhone").isEqualTo(expected.getMobilePhone()))
            .satisfies(a -> assertThat(a.getWebsiteUrl()).as("check websiteUrl").isEqualTo(expected.getWebsiteUrl()))
            .satisfies(a -> assertThat(a.getAmazonWishlistUrl()).as("check amazonWishlistUrl").isEqualTo(expected.getAmazonWishlistUrl()))
            .satisfies(a -> assertThat(a.getLastLoginDate()).as("check lastLoginDate").isEqualTo(expected.getLastLoginDate()))
            .satisfies(a -> assertThat(a.getBiography()).as("check biography").isEqualTo(expected.getBiography()))
            .satisfies(a -> assertThat(a.getIsFree()).as("check isFree").isEqualTo(expected.getIsFree()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserProfileUpdatableRelationshipsEquals(UserProfile expected, UserProfile actual) {
        assertThat(actual)
            .as("Verify UserProfile relationships")
            .satisfies(a -> assertThat(a.getStateOfResidence()).as("check stateOfResidence").isEqualTo(expected.getStateOfResidence()));
    }
}
