package com.monsterdam.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VideoStoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVideoStoryAllPropertiesEquals(VideoStory expected, VideoStory actual) {
        assertVideoStoryAutoGeneratedPropertiesEquals(expected, actual);
        assertVideoStoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVideoStoryAllUpdatablePropertiesEquals(VideoStory expected, VideoStory actual) {
        assertVideoStoryUpdatableFieldsEquals(expected, actual);
        assertVideoStoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVideoStoryAutoGeneratedPropertiesEquals(VideoStory expected, VideoStory actual) {
        assertThat(actual)
            .as("Verify VideoStory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVideoStoryUpdatableFieldsEquals(VideoStory expected, VideoStory actual) {
        assertThat(actual)
            .as("Verify VideoStory relevant properties")
            .satisfies(a -> assertThat(a.getThumbnailS3Key()).as("check thumbnailS3Key").isEqualTo(expected.getThumbnailS3Key()))
            .satisfies(a -> assertThat(a.getContentS3Key()).as("check contentS3Key").isEqualTo(expected.getContentS3Key()))
            .satisfies(a -> assertThat(a.getDuration()).as("check duration").isEqualTo(expected.getDuration()))
            .satisfies(a -> assertThat(a.getLikeCount()).as("check likeCount").isEqualTo(expected.getLikeCount()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVideoStoryUpdatableRelationshipsEquals(VideoStory expected, VideoStory actual) {
        assertThat(actual)
            .as("Verify VideoStory relationships")
            .satisfies(a -> assertThat(a.getCreator()).as("check creator").isEqualTo(expected.getCreator()));
    }
}
