package com.monsterdam.app.domain;

import static com.monsterdam.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ViewerWalletAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertViewerWalletAllPropertiesEquals(ViewerWallet expected, ViewerWallet actual) {
        assertViewerWalletAutoGeneratedPropertiesEquals(expected, actual);
        assertViewerWalletAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertViewerWalletAllUpdatablePropertiesEquals(ViewerWallet expected, ViewerWallet actual) {
        assertViewerWalletUpdatableFieldsEquals(expected, actual);
        assertViewerWalletUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertViewerWalletAutoGeneratedPropertiesEquals(ViewerWallet expected, ViewerWallet actual) {
        assertThat(actual)
            .as("Verify ViewerWallet auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertViewerWalletUpdatableFieldsEquals(ViewerWallet expected, ViewerWallet actual) {
        assertThat(actual)
            .as("Verify ViewerWallet relevant properties")
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getTransactionType()).as("check transactionType").isEqualTo(expected.getTransactionType()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertViewerWalletUpdatableRelationshipsEquals(ViewerWallet expected, ViewerWallet actual) {
        assertThat(actual)
            .as("Verify ViewerWallet relationships")
            .satisfies(a -> assertThat(a.getPayment()).as("check payment").isEqualTo(expected.getPayment()))
            .satisfies(a -> assertThat(a.getViewer()).as("check viewer").isEqualTo(expected.getViewer()));
    }
}
